### ISSUE TITLE
Matrix-native forms need styling

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/matrix-helpers#125]
Forms created using the built-in Matrix techniques need styling, as requested by Shan Hogan in the JCU Web # framework-development Slack around 2017-06-08 9:39.

I've added minimal formatting for question titles and notes in `web-framework/designs/explore.min.css/form-formatting.css`, this can be expanded but remember to check all the various form types.

David knocked up some speculative CSS in-browser:
```css
.sq-form-required-field {
	color: red;
	border-bottom: 0px !important;
}

.sq-form-required-field-note {
	background: lightgreen;
	padding: 1rem;
	margin-bottom: 1rem;
	border-radius: 1rem;
}

.sq-form-question-title {
	margin-bottom: 0;
}

.sq-form-question-note {
	font-size: 80%;
	color: grey;
	display: block;
	margin-bottom: 1rem;
}

.sq-form-field {
	width: 100%;
}
```
