### ISSUE TITLE
CSS "Basic Minifier" (cssmin.php) breaks rules with attribute selectors

### ISSUE THREAD

**Issue by davidjb** [jcu-eresearch/matrix-helpers#92]
Trying to use a `CSS File Folder` in Matrix with a CSS file with the following rule (a valid, a CSS attribute selector):

```css
.bg--cover[style*="background-attachment: fixed;"] {
  background-attachment: scroll !important;
}
```

turns the above rule into the following:

```css
.bg--cover[style*="background-attachment:fixed;"] {background-attachment: scroll !important;}
```

This has one subtle, but *breaking* change -- the removal of the whitespace inside the attribute selector.  This causes the selector break as CSS requires the (sub)string be literally matched.  Because the intended DOM element has a `style` attribute of `background-attachment: fixed`, the 'minified' selector no longer matches.

A workaround *could* be to change the source to match what the minifier is producing, but the core issue here is that minifier produces inconsistent output.  For now, switching back to merging-only on the CSS File Folder works.

Tested with Matrix 5.4.0.3
